// Danh mục ngân hàng Việt Nam — dùng cho dropdown gợi ý (datalist) ở ô "Ngân hàng".
// Đây chỉ là gợi ý lọc-khi-gõ; ô vẫn cho nhập tự do để tương thích dữ liệu cũ
// (vd "Techcom bank", "k có stk").
export const VN_BANKS: string[] = [
  "Vietcombank",
  "VietinBank",
  "BIDV",
  "Agribank",
  "Techcombank",
  "MB Bank",
  "ACB",
  "VPBank",
  "TPBank",
  "Sacombank",
  "HDBank",
  "VIB",
  "SHB",
  "MSB",
  "OCB",
  "SeABank",
  "Eximbank",
  "LPBank",
  "SCB",
  "Nam A Bank",
  "ABBank",
  "PVcomBank",
  "Bac A Bank",
  "Saigonbank",
  "VietABank",
  "BVBank",
  "Kienlongbank",
  "NCB",
  "PGBank",
  "Vietbank",
  "BaoVietBank",
  "CBBank",
  "GPBank",
  "OceanBank (MBV)",
  "DongA Bank (Vikki)",
  "Cake by VPBank",
  "Timo",
  "Standard Chartered",
  "Shinhan Bank",
  "HSBC",
  "UOB",
  "Woori Bank",
  "Public Bank",
  "CIMB",
  "Hong Leong Bank",
];
